/*
 * Generated by GBuilder
 * Application: Untitled
 * Platform: desktop
 * Date: 1/12/2026, 1:18:17 PM
 */

#include <Gooey/gooey.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/******************************************************************************
 *                              DEFINES
 ******************************************************************************/

/* Widget index macros */
/* BUTTON indices */
#define BUTTON_0                                 (0U)

/* TEXTBOX indices */
#define TXTBOX_1                                 (0U)

/******************************************************************************
 *                              TYPEDEFS
 ******************************************************************************/

/* Application state structure */
typedef struct
{
    GooeyWindow *window;
    GooeyMenu *menu;
    GooeyButton **buttons;
    GooeyTextbox **textboxs;
    uint32_t button_count;
    uint32_t textbox_count;
    uint32_t slider_count;
    uint32_t checkbox_count;
    uint32_t label_count;
    uint32_t canvas_count;
    uint32_t image_count;
    uint32_t dropsurface_count;
    uint32_t dropdown_count;
    uint32_t list_count;
    uint32_t progressbar_count;
    uint32_t meter_count;
    uint32_t gswitch_count;
    uint32_t container_count;
    uint32_t tabs_count;
    uint32_t plot_count;
    uint32_t radiobuttongroup_count;
    void *user_data;
} AppState;

static void textclbk_wrapper(char* text, void* user_pointer);
void textclbk(AppState* state, char* text);
static void test_wrapper(void* user_pointer);
void test(AppState* state);

/******************************************************************************
 *                         PRIVATE FUNCTIONS
 ******************************************************************************/

static void textclbk_wrapper(char* text, void* user_pointer)
{
    AppState* state = (AppState*)user_pointer;
    textclbk(state, text);
}

static void test_wrapper(void* user_pointer)
{
    AppState* state = (AppState*)user_pointer;
    test(state);
}

/******************************************************************************
 *                         PUBLIC FUNCTIONS
 ******************************************************************************/
void textclbk(AppState* state, char* text) {
    // text contains the current input text

}

void test(AppState* state) {
    // Your code here
    GooeyTextbox_SetText(state->textboxs[TXTBOX_1], "test text");
}

/******************************************************************************
 *                         MAIN FUNCTION
 ******************************************************************************/

int main(void)
{
    AppState state = {0};

    /* Allocate widget arrays */
    state.buttons = (GooeyButton **)malloc(sizeof(GooeyButton*) * 1U);
    if (state.buttons == NULL)
    {
        return -1;
    }
    state.button_count = 1U;

    state.textboxs = (GooeyTextbox **)malloc(sizeof(GooeyTextbox*) * 1U);
    if (state.textboxs == NULL)
    {
        return -1;
    }
    state.textbox_count = 1U;

    /* Initialize GooeyGUI framework */
    Gooey_Init();

    /* Create main application window */
    state.window = GooeyWindow_Create("My Window", 0, 0, 800, 600, true);
    if (state.window == NULL)
    {
        return -1;
    }

    GooeyWindow_MakeVisible(state.window, false);
    GooeyWindow_MakeResizable(state.window, false);

    /* Create button */
    GooeyButton* button_3 = GooeyButton_Create("Button", 41, 220, 100, 30, test_wrapper, (void*)&state);
    state.buttons[0] = button_3;
    /* Create textbox (macro: TXTBOX_1) */
    GooeyTextbox* input_1 = GooeyTextBox_Create(195, 113, 150, 24, "", false, textclbk_wrapper, (void*)&state);
    state.textboxs[0] = input_1;

    /* Register widgets with window */
    GooeyWindow_RegisterWidget(state.window, button_3);
    GooeyWindow_RegisterWidget(state.window, input_1);

    /* Run main application loop */
    GooeyWindow_Run(1, state.window);

    /* Cleanup resources */
    GooeyWindow_Cleanup(1, state.window);
    free(state.buttons);
    state.buttons = NULL;
    free(state.textboxs);
    state.textboxs = NULL;
    return 0;
}
