/*
 * Generated by GBuilder on 1/4/2026, 6:50:33 PM
 * Application: Untitled
 * Platform: desktop
 */

#include <Gooey/gooey.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>

/******************************************************************************
 *                              DEFINES
 ******************************************************************************/

/* Widget index macros - Use these instead of hardcoded indices */
/* Example: state.buttons[BTN_OK] instead of state.buttons[0] */

/* BUTTON indices */
#define BUTTON_0                     (0U)

/******************************************************************************
 *                              TYPEDEFS
 ******************************************************************************/

/* Application state structure */
typedef struct
{
    GooeyWindow *window;
    GooeyMenu *menu;
    GooeyButton **buttons;
    uint32_t button_count;
    uint32_t textbox_count;
    uint32_t slider_count;
    uint32_t checkbox_count;
    uint32_t label_count;
    uint32_t canvas_count;
    uint32_t image_count;
    uint32_t dropsurface_count;
    uint32_t dropdown_count;
    uint32_t list_count;
    uint32_t progressbar_count;
    uint32_t meter_count;
    uint32_t switch_count;
    uint32_t container_count;
    uint32_t tab_count;
    uint32_t plot_count;
    uint32_t radiobuttongroup_count;
    void *user_data; /* For custom user data */
} AppState;

static void test_wrapper(void* user_pointer);
void test(AppState* state);

/******************************************************************************
 *                         PRIVATE FUNCTIONS
 ******************************************************************************/

/**
 * @brief  Wrapper function for test
 * @param  user_pointer: Pointer to user data (AppState)
 * @retval None
 */
static void test_wrapper(void* user_pointer)
{
    AppState* state = (AppState*)user_pointer;
    test(state);
}

/******************************************************************************
 *                         PUBLIC FUNCTIONS
 ******************************************************************************/

/**
 * @brief  test callback function
 * @param  state: Pointer to application state
 * @retval None
 */
void test(AppState* state) {
        /* Access widgets using macros */
    // Your code here
}

/******************************************************************************
 *                         MAIN FUNCTION
 ******************************************************************************/

/**
 * @brief  Main application entry point
 * @param  None
 * @retval int: Application exit code
 */
int main(void)
{
    /* Local variables */
    AppState state = {0};
    /* Allocate widget arrays */
    state.buttons = (GooeyButton **)malloc(sizeof(GooeyButton*) * 1U);
    if (state.buttons == NULL)
    {
        /* Handle allocation error */
        return -1;
    }
    state.button_count = 1U;

    /* Initialize GooeyGUI framework */
    Gooey_Init();

    /* Create main application window */
    state.window = GooeyWindow_Create("My Window", 0, 0, 800, 600, true);
    if (state.window == NULL)
    {
        /* Handle window creation error */
        return -1;
    }

    GooeyWindow_MakeVisible(state.window, false);
    GooeyWindow_MakeResizable(state.window, false);

    /* Create button */
    GooeyButton* button_1 = GooeyButton_Create("Button", 213, 238, 100, 30, test_wrapper, (void*)&state);
    state.buttons[0] = button_1;

    /* Register all widgets with the window */
    GooeyWindow_RegisterWidget(state.window, button_1);

    /* Run the main application loop */
    GooeyWindow_Run(1, state.window);

    /* Cleanup resources */
    GooeyWindow_Cleanup(1, state.window);

    free(state.buttons);
    state.buttons = NULL;
    return 0;
}
