import state from "./state.js";
import { getWidgetsInContainer, getWidgetsInTab } from "./hierarchyManager.js";

export async function generateC() {
    let cCode =
        "// Generated by GBuilder on " + new Date().toLocaleString() + "\n";

    if (state.projectSettings.platform == "embedded") {
        cCode += `#include <gooey.h>\n`;
        cCode += `#include <Arduino.h>\n\n`;
    } else {
        cCode += `#include <Gooey/gooey.h>\n\n`;
    }

    cCode += `/* Global application state */\n`;
    cCode += `typedef struct {\n`;
    cCode += `    GooeyWindow *window;\n`;
    cCode += `    GooeyMenu *menu;\n`;

    const usedWidgetTypes = new Set();
    state.previewContent.querySelectorAll(".widget").forEach((widget) => {
        usedWidgetTypes.add(widget.dataset.type);
    });

    if (usedWidgetTypes.has("Button")) cCode += `    GooeyButton **buttons;\n`;
    if (usedWidgetTypes.has("Input")) cCode += `    GooeyTextbox **textboxs;\n`;
    if (usedWidgetTypes.has("Slider")) cCode += `    GooeySlider **sliders;\n`;
    if (usedWidgetTypes.has("Checkbox"))
        cCode += `    GooeyCheckbox **checkboxes;\n`;
    if (usedWidgetTypes.has("Label")) cCode += `    GooeyLabel **labels;\n`;
    if (usedWidgetTypes.has("Canvas")) cCode += `    GooeyCanvas **canvases;\n`;
    if (usedWidgetTypes.has("Image")) cCode += `    GooeyImage **images;\n`;
    if (usedWidgetTypes.has("DropSurface"))
        cCode += `    GooeyDropSurface **dropsurfaces;\n`;
    if (usedWidgetTypes.has("Dropdown"))
        cCode += `    GooeyDropdown **dropdowns;\n`;
    if (usedWidgetTypes.has("List")) cCode += `    GooeyList **lists;\n`;
    if (usedWidgetTypes.has("Progressbar"))
        cCode += `    GooeyProgressBar **progressbars;\n`;
    if (usedWidgetTypes.has("Meter")) cCode += `    GooeyMeter **meters;\n`;
    if (usedWidgetTypes.has("GSwitch"))
        cCode += `    GooeySwitch **switches;\n`;
    if (usedWidgetTypes.has("Container"))
        cCode += `    GooeyContainer **containers;\n`;
    if (usedWidgetTypes.has("Tabs")) cCode += `    GooeyTabs **tabs;\n`;
    if (usedWidgetTypes.has("Plot")) cCode += `    GooeyPlot **plots;\n`;
    if (usedWidgetTypes.has("RadioButtonGroup"))
        cCode += `    GooeyRadioButtonGroup **radiobuttongroups;\n`;

    cCode += `    int button_count;\n`;
    cCode += `    int textbox_count;\n`;
    cCode += `    int slider_count;\n`;
    cCode += `    int checkbox_count;\n`;
    cCode += `    int label_count;\n`;
    cCode += `    int canvas_count;\n`;
    cCode += `    int image_count;\n`;
    cCode += `    int dropsurface_count;\n`;
    cCode += `    int dropdown_count;\n`;
    cCode += `    int list_count;\n`;
    cCode += `    int progressbar_count;\n`;
    cCode += `    int meter_count;\n`;
    cCode += `    int switch_count;\n`;
    cCode += `    int container_count;\n`;
    cCode += `    int tab_count;\n`;
    cCode += `    int plot_count;\n`;
    cCode += `    int radiobuttongroup_count;\n`;
    cCode += `    void *user_data; /* For custom user data */\n`;
    cCode += `} AppState;\n\n`;

    const callbacks = [];

    Object.entries(state.widgetCallbacks).forEach(
        ([widgetId, callbackData]) => {
            const widget = document.querySelector(
                `.widget[data-id="${widgetId}"]`,
            );
            if (!widget || !callbackData.callbackName) return;

            const callbackName = callbackData.callbackName;

            Object.entries(callbackData).forEach(([type, code]) => {
                if (type.endsWith("_code") && code && code.trim()) {
                    const lines = code.split("\n");
                    if (lines.length > 0) {
                        const firstLine = lines[0].trim();
                        if (
                            firstLine.startsWith("void ") &&
                            firstLine.includes("(")
                        ) {
                            const funcName = firstLine
                                .substring(5, firstLine.indexOf("("))
                                .trim();

                            callbacks.push({
                                funcName: funcName,
                                callbackName: callbackName,
                                code: code,
                                widgetType: widget.dataset.type,
                            });

                            const wrapperSignature = `void ${callbackName}_wrapper(void* state_ptr);\n`;
                            if (!cCode.includes(wrapperSignature)) {
                                cCode += wrapperSignature;
                            }
                        }
                    }
                }
            });
        },
    );

    cCode += `\n/* Callback functions */\n`;

    callbacks.forEach(({ funcName, callbackName, code, widgetType }) => {
        const callbackCode = code.replace(
            `void ${funcName}(void* user_data)`,
            `void ${funcName}(AppState* state)`,
        );
        cCode += callbackCode + "\n\n";

        cCode += `void ${callbackName}_wrapper(void* state_ptr) {\n`;
        cCode += `    AppState* state = (AppState*)state_ptr;\n`;

        switch (widgetType) {
            case "Slider":
                cCode += `    // Note: Slider value would need to be passed separately\n`;
                cCode += `    ${funcName}(state);\n`;
                break;
            case "Checkbox":
                cCode += `    // Note: Checkbox state would need to be passed separately\n`;
                cCode += `    ${funcName}(state);\n`;
                break;
            case "Input":
                cCode += `    // Note: Text would need to be passed separately\n`;
                cCode += `    ${funcName}(state);\n`;
                break;
            default:
                cCode += `    ${funcName}(state);\n`;
        }
        cCode += `}\n\n`;
    });

    switch (state.projectSettings.platform) {
        case "embedded":
            cCode += `void setup()\n{\n`;
            break;
        case "desktop":
            cCode += `int main()\n{\n`;
            break;
        default:
            cCode += `int main()\n{\n`;
            break;
    }

    cCode += `    /* Initialize application state */\n`;
    cCode += `    AppState state = {0};\n\n`;

    const widgetCounts = {
        button: 0,
        textbox: 0,
        slider: 0,
        checkbox: 0,
        label: 0,
        canvas: 0,
        image: 0,
        dropsurface: 0,
        dropdown: 0,
        list: 0,
        progressbar: 0,
        meter: 0,
        gswitch: 0,
        container: 0,
        tabs: 0,
        plot: 0,
        radiobuttongroup: 0,
    };

    state.previewContent.querySelectorAll(".widget").forEach((widget) => {
        const type =
            widget.dataset.type.toLowerCase() == "input"
                ? "textbox"
                : widget.dataset.type.toLowerCase();
        if (widgetCounts.hasOwnProperty(type)) {
            widgetCounts[type]++;
        }
    });

    cCode += `    /* Allocate widget arrays */\n`;
    Object.entries(widgetCounts).forEach(([type, count]) => {
        if (count > 0) {
            cCode += `    state.${type}s = malloc(sizeof(${getWidgetTypeName(type)}*) * ${count});\n`;
            cCode += `    state.${type}_count = ${count};\n`;
        }
    });

    cCode += `\n    /* Initialize GooeyGUI */\n`;
    cCode += `    Gooey_Init();\n\n`;

    cCode += `    /* Create window */\n`;
    cCode += `    state.window = GooeyWindow_Create("${document.getElementById("win-title").value}", 0, 0, ${document.getElementById("win-width").value}, ${document.getElementById("win-height").value}, true);\n\n`;

    if (state.previewWindow.dataset.debug_overlay === "true")
        cCode += `    GooeyWindow_EnableDebugOverlay(state.window, true);\n`;

    if (state.previewWindow.dataset.cont_redraw === "true")
        cCode += `    GooeyWindow_SetContinuousRedraw(state.window);\n`;

    if (state.previewWindow.dataset.is_visible === "true")
        cCode += `    GooeyWindow_MakeVisible(state.window, true);\n`;
    else cCode += `    GooeyWindow_MakeVisible(state.window, false);\n`;

    if (state.previewWindow.dataset.is_resizable === "true")
        cCode += `    GooeyWindow_MakeResizable(state.window, true);\n`;
    else cCode += `    GooeyWindow_MakeResizable(state.window, false);\n\n`;

    const widgetIndices = {
        button: 0,
        textbox: 0,
        slider: 0,
        checkbox: 0,
        label: 0,
        canvas: 0,
        image: 0,
        dropsurface: 0,
        dropdown: 0,
        list: 0,
        progressbar: 0,
        meter: 0,
        gswitch: 0,
        container: 0,
        tabs: 0,
        plot: 0,
        radiobuttongroup: 0,
    };

    state.widgetCounter = 0;
    let widgetVars = new Set();
    let widgetRegistrations = [];
    let processedWidgetIds = new Set();

    function generateUniqueVarName(baseName) {
        let counter = 1;
        let varName = baseName;

        while (widgetVars.has(varName)) {
            varName = `${baseName}_${counter++}`;
        }

        widgetVars.add(varName);
        return varName;
    }

    function processWidgetC(
        widget,
        indent,
        parentVar = null,
        containerId = null,
        tabId = null,
    ) {
        const widgetId = widget.dataset.id;

        if (processedWidgetIds.has(widgetId)) {
            return "";
        }

        processedWidgetIds.add(widgetId);

        let type = widget.dataset.type;
        let x = parseInt(widget.style.left) || 0;
        let y = parseInt(widget.style.top) || 0;
        let width = parseInt(widget.style.width) || 100;
        let height = parseInt(widget.style.height) || 30;

        let text = widget.textContent || "";
        text = text.replace(/"/g, '\\"');

        let callbackData = state.widgetCallbacks[widgetId];
        let callbackName = callbackData?.callbackName || "";

        // Use wrapper callback that passes AppState
        let callbackWithData = callbackName
            ? `${callbackName}_wrapper, (void*)&state`
            : "NULL, NULL";

        let widgetVar = widget.dataset.widgetVar;
        if (!widgetVar || widgetVars.has(widgetVar)) {
            widgetVar = generateUniqueVarName(
                `${type.toLowerCase()}_${state.widgetCounter++}`,
            );
            widget.dataset.widgetVar = widgetVar;
        } else {
            widgetVars.add(widgetVar);
        }

        let widgetCode = "";
        const typeLower = type.toLowerCase();

        switch (type) {
            case "Button":
                widgetCode += `${indent}/* Create button */\n`;
                widgetCode += `${indent}GooeyButton* ${widgetVar} = GooeyButton_Create("${text}", ${x}, ${y}, ${width}, ${height}, ${callbackWithData});\n`;
                widgetCode += `${indent}state.buttons[${widgetIndices.button++}] = ${widgetVar};\n`;
                break;

            case "Input":
                widgetCode += `${indent}/* Create textbox */\n`;
                widgetCode += `${indent}GooeyTextbox* ${widgetVar} = GooeyTextBox_Create(${x}, ${y}, ${width}, ${height}, "${text}", false, ${callbackWithData});\n`;
                widgetCode += `${indent}state.textboxs[${widgetIndices.textbox++}] = ${widgetVar};\n`;
                break;

            case "Slider":
                let minValue = widget.dataset.minValue || 0;
                let maxValue = widget.dataset.maxValue || 100;
                let showHints = widget.dataset.showHints || "false";
                widgetCode += `${indent}/* Create slider */\n`;
                widgetCode += `${indent}GooeySlider* ${widgetVar} = GooeySlider_Create(${x}, ${y}, ${width}, ${minValue}, ${maxValue}, ${showHints}, ${callbackWithData});\n`;
                widgetCode += `${indent}state.sliders[${widgetIndices.slider++}] = ${widgetVar};\n`;
                break;

            case "Checkbox":
                widgetCode += `${indent}/* Create checkbox */\n`;
                widgetCode += `${indent}GooeyCheckbox* ${widgetVar} = GooeyCheckbox_Create(${x}, ${y}, "${text}", ${callbackWithData});\n`;
                widgetCode += `${indent}state.checkboxes[${widgetIndices.checkbox++}] = ${widgetVar};\n`;
                break;

            case "Label":
                widgetCode += `${indent}/* Create label */\n`;
                widgetCode += `${indent}GooeyLabel* ${widgetVar} = GooeyLabel_Create("${text}", 18.0f, ${x}, ${y});\n`;
                widgetCode += `${indent}state.labels[${widgetIndices.label++}] = ${widgetVar};\n`;
                break;

            case "Canvas":
                widgetCode += `${indent}/* Create canvas */\n`;
                widgetCode += `${indent}GooeyCanvas* ${widgetVar} = GooeyCanvas_Create(${x}, ${y}, ${width}, ${height}, NULL, NULL);\n`;
                widgetCode += `${indent}state.canvases[${widgetIndices.canvas++}] = ${widgetVar};\n`;
                break;

            case "Image":
                let imagePath =
                    widget.dataset.relativePath || "./assets/example.png";
                widgetCode += `${indent}/* Create image */\n`;
                widgetCode += `${indent}GooeyImage* ${widgetVar} = GooeyImage_Create("${imagePath}", ${x}, ${y}, ${width}, ${height}, ${callbackWithData});\n`;
                widgetCode += `${indent}state.images[${widgetIndices.image++}] = ${widgetVar};\n`;
                break;

            case "DropSurface":
                let message =
                    widget.dataset.dropsurfaceMessage || "Drop files here..";
                widgetCode += `${indent}/* Create drop surface */\n`;
                widgetCode += `${indent}GooeyDropSurface* ${widgetVar} = GooeyDropSurface_Create(${x}, ${y}, ${width}, ${height}, "${message}", ${callbackWithData});\n`;
                widgetCode += `${indent}state.dropsurfaces[${widgetIndices.dropsurface++}] = ${widgetVar};\n`;
                break;

            case "Dropdown":
                let dropdownOptionsList = widget.dataset.dropdownOptions
                    ? widget.dataset.dropdownOptions.split(",")
                    : [];
                let dropdownOptionsListLength = dropdownOptionsList.length;
                dropdownOptionsList = dropdownOptionsList.map(
                    (o) => `"${o.trim()}"`,
                );

                if (dropdownOptionsListLength > 0) {
                    widgetCode += `${indent}const char* options_${widgetVar}[${dropdownOptionsListLength}] = {${dropdownOptionsList.join(", ")}};\n`;
                    widgetCode += `${indent}GooeyDropdown* ${widgetVar} = GooeyDropdown_Create(${x}, ${y}, ${width}, ${height}, options_${widgetVar}, ${dropdownOptionsListLength}, ${callbackWithData});\n`;
                } else {
                    widgetCode += `${indent}GooeyDropdown* ${widgetVar} = GooeyDropdown_Create(${x}, ${y}, ${width}, ${height}, NULL, 0, ${callbackWithData});\n`;
                }
                widgetCode += `${indent}state.dropdowns[${widgetIndices.dropdown++}] = ${widgetVar};\n`;
                break;

            case "List":
                let listOptionsList = widget.dataset.listOptions
                    ? JSON.parse(widget.dataset.listOptions)
                    : [];
                widgetCode += `${indent}/* Create list */\n`;
                widgetCode += `${indent}GooeyList* ${widgetVar} = GooeyList_Create(${x}, ${y}, ${width}, ${height}, ${callbackWithData});\n`;
                widgetCode += `${indent}state.lists[${widgetIndices.list++}] = ${widgetVar};\n`;

                listOptionsList.forEach((item) => {
                    widgetCode += `${indent}GooeyList_AddItem(${widgetVar}, "${item.name || ""}", "${item.description || ""}");\n`;
                });
                break;

            case "Menu":
                widgetCode += `${indent}/* Create menu */\n`;
                widgetCode += `${indent}GooeyMenu* ${widgetVar} = GooeyMenu_Set(state.window);\n`;
                widgetCode += `${indent}state.menu = ${widgetVar};\n`;
                break;

            case "RadioButtonGroup":
                widgetCode += `${indent}/* Create radio button group */\n`;
                widgetCode += `${indent}GooeyRadioButtonGroup* ${widgetVar} = GooeyRadioButtonGroup_Create();\n`;
                widgetCode += `${indent}state.radiobuttongroups[${widgetIndices.radiobuttongroup++}] = ${widgetVar};\n`;
                break;

            case "Progressbar":
                let progressValue = widget.dataset.value || 50;
                widgetCode += `${indent}/* Create progressbar */\n`;
                widgetCode += `${indent}GooeyProgressBar* ${widgetVar} = GooeyProgressBar_Create(${x}, ${y}, ${width}, ${height}, ${progressValue});\n`;
                widgetCode += `${indent}state.progressbars[${widgetIndices.progressbar++}] = ${widgetVar};\n`;
                break;

            case "Meter":
                let meterValue = widget.dataset.value || 50;
                let meterLabel = widget.dataset.label || "Meter";
                widgetCode += `${indent}/* Create meter */\n`;
                widgetCode += `${indent}GooeyMeter* ${widgetVar} = GooeyMeter_Create(${x}, ${y}, ${width}, ${height}, ${meterValue}, "${meterLabel}", NULL);\n`;
                widgetCode += `${indent}state.meters[${widgetIndices.meter++}] = ${widgetVar};\n`;
                break;

            case "GSwitch":
                let isToggled = widget.classList.contains("checked")
                    ? "true"
                    : "false";
                let showSwitchHints = widget.dataset.showHints || "false";
                widgetCode += `${indent}/* Create switch */\n`;
                widgetCode += `${indent}GooeySwitch* ${widgetVar} = GooeySwitch_Create(${x}, ${y}, ${isToggled}, ${showSwitchHints}, ${callbackWithData});\n`;
                widgetCode += `${indent}state.switches[${widgetIndices.gswitch++}] = ${widgetVar};\n`;
                break;

            case "Container":
                widgetCode += `${indent}/* Create container */\n`;
                widgetCode += `${indent}GooeyContainer* ${widgetVar} = GooeyContainer_Create(${x}, ${y}, ${width}, ${height});\n`;
                widgetCode += `${indent}state.containers[${widgetIndices.container++}] = ${widgetVar};\n`;

                const containerNames = JSON.parse(
                    widget.dataset.containerNames || '["Container 0"]',
                );

                containerNames.forEach((name, index) => {
                    widgetCode += `${indent}GooeyContainer_InsertContainer(${widgetVar}); // ${name}\n`;
                });

                const activeContainer = parseInt(
                    widget.dataset.activeContainer || "0",
                );
                widgetCode += `${indent}GooeyContainer_SetActiveContainer(${widgetVar}, ${activeContainer});\n`;

                containerNames.forEach((name, index) => {
                    const containerWidgets = getWidgetsInContainer(
                        widget,
                        index,
                    );
                    containerWidgets.forEach((childData) => {
                        const childCode = processWidgetC(
                            childData.widget,
                            indent + "    ",
                            widgetVar,
                            index,
                            null,
                        );
                        widgetCode += childCode;
                        widgetCode += `${indent}GooeyContainer_AddWidget(state.window, ${widgetVar}, ${index}, ${childData.widget.dataset.widgetVar});\n`;
                    });
                });
                break;

            case "Tabs":
                widgetCode += `${indent}/* Create tabs */\n`;
                const isSidebar = widget.dataset.isSidebar || "false";
                widgetCode += `${indent}GooeyTabs* ${widgetVar} = GooeyTabs_Create(${x}, ${y}, ${width}, ${height}, ${isSidebar});\n`;
                widgetCode += `${indent}state.tabs[${widgetIndices.tabs++}] = ${widgetVar};\n`;

                const tabNames = JSON.parse(
                    widget.dataset.tabNames || '["Tab 1", "Tab 2"]',
                );

                tabNames.forEach((name, index) => {
                    widgetCode += `${indent}GooeyTabs_InsertTab(${widgetVar}, "${name}");\n`;
                });

                const activeTab = parseInt(widget.dataset.activeTab || "0");
                widgetCode += `${indent}GooeyTabs_SetActiveTab(${widgetVar}, ${activeTab});\n`;

                tabNames.forEach((name, index) => {
                    const tabWidgets = getWidgetsInTab(widget, index);
                    tabWidgets.forEach((childData) => {
                        const childCode = processWidgetC(
                            childData.widget,
                            indent + "    ",
                            widgetVar,
                            null,
                            index,
                        );
                        widgetCode += childCode;
                        widgetCode += `${indent}GooeyTabs_AddWidget(state.window, ${widgetVar}, ${index}, ${childData.widget.dataset.widgetVar});\n`;
                    });
                });
                break;

            case "Plot":
                widgetCode += `${indent}/* Create plot */\n`;
                widgetCode += `${indent}float x_data_${widgetVar}[]  = {${widget.dataset.xAxisDataList}};\n`;
                widgetCode += `${indent}float y_data_${widgetVar}[]  = {${widget.dataset.yAxisDataList}};\n`;
                widgetCode += `${indent}float x_step_${widgetVar} = 1.0f;\n`;
                widgetCode += `${indent}float y_step_${widgetVar} = 1.0f;\n`;

                let selectedType;
                switch (widget.dataset.plotType) {
                    case "line":
                        selectedType = "GOOEY_PLOT_LINE";
                        break;
                    case "scatter":
                        selectedType = "GOOEY_PLOT_SCATTER";
                        break;
                    case "bar":
                        selectedType = "GOOEY_PLOT_BAR";
                        break;
                    case "pie":
                        selectedType = "GOOEY_PLOT_PIE";
                        break;
                    default:
                        selectedType = "GOOEY_PLOT_LINE";
                        break;
                }

                widgetCode += `${indent}GooeyPlotData* plotData_${widgetVar} = malloc(sizeof(GooeyPlotData));\n`;
                widgetCode += `${indent}*plotData_${widgetVar} = (GooeyPlotData) {x_data_${widgetVar}, y_data_${widgetVar}, ${widget.dataset.xAxisDataList.split(",").length}, "${widget.dataset.xAxisLabel}", x_step_${widgetVar}, "${widget.dataset.yAxisLabel}", y_step_${widgetVar}, "${widget.dataset.plotTitle}", -1, -1, -1, -1, NULL, ${selectedType}};\n`;
                widgetCode += `${indent}GooeyPlot* ${widgetVar} = GooeyPlot_Create(${selectedType}, plotData_${widgetVar}, ${x}, ${y}, ${width}, ${height});\n`;
                widgetCode += `${indent}state.plots[${widgetIndices.plot++}] = ${widgetVar};\n`;
                break;

            case "VerticalLayout":
            case "HorizontalLayout":
                let layoutType =
                    type === "VerticalLayout"
                        ? "LAYOUT_VERTICAL"
                        : "LAYOUT_HORIZONTAL";
                widgetCode += `${indent}/* Create layout */\n`;
                widgetCode += `${indent}GooeyLayout* ${widgetVar} = GooeyLayout_Create(${layoutType}, ${x}, ${y}, ${width}, ${height});\n`;

                Array.from(widget.children).forEach((child) => {
                    if (
                        child.classList.contains("widget") &&
                        !child.classList.contains("resize-handle")
                    ) {
                        const childCode = processWidgetC(
                            child,
                            indent + "    ",
                            widgetVar,
                        );
                        widgetCode += childCode;
                        widgetCode += `${indent}GooeyLayout_AddChild(state.window, ${widgetVar}, ${child.dataset.widgetVar});\n`;
                    }
                });

                widgetCode += `${indent}GooeyLayout_Build(${widgetVar});\n`;
                break;
        }

        /* ---------------- WINDOW REGISTRATION ---------------- */
        if (type !== "Menu" && type !== "RadioButtonGroup" && !parentVar) {
            widgetRegistrations.push(
                `${indent}GooeyWindow_RegisterWidget(state.window, ${widgetVar});\n`,
            );
        }

        return widgetCode;
    }

    const allWidgetIds = new Set();
    state.previewContent.querySelectorAll(".widget").forEach((widget) => {
        allWidgetIds.add(widget.dataset.id);
    });

    const containerTabWidgets = Array.from(
        state.previewContent.querySelectorAll(".widget"),
    ).filter((widget) => {
        const type = widget.dataset.type;
        return type === "Container" || type === "Tabs";
    });

    containerTabWidgets.forEach((widget) => {
        cCode += processWidgetC(widget, "    ");
    });

    state.previewContent.querySelectorAll(".widget").forEach((widget) => {
        if (!widget.parentElement.classList.contains("layout")) {
            const widgetId = widget.dataset.id;

            if (processedWidgetIds.has(widgetId)) {
                return;
            }

            const type = widget.dataset.type;
            if (type === "Container" || type === "Tabs") {
                return;
            }

            const hierarchy = state.widgetHierarchy.get(widgetId);
            if (!hierarchy || (!hierarchy.containerId && !hierarchy.tabId)) {
                cCode += processWidgetC(widget, "    ");
            }
        }
    });

    if (widgetRegistrations.length > 0) {
        cCode += `\n    /* Register widgets with window */\n`;
        widgetRegistrations.forEach((reg) => {
            cCode += reg;
        });
    }

    cCode += `\n    /* Run the application */\n`;
    cCode += `    GooeyWindow_Run(1, state.window);\n\n`;
    cCode += `    /* Cleanup */\n`;
    cCode += `    GooeyWindow_Cleanup(1, state.window);\n\n`;

    Object.entries(widgetCounts).forEach(([type, count]) => {
        if (count > 0) {
            cCode += `    free(state.${type}s);\n`;
        }
    });

    if (state.projectSettings.platform == "embedded") {
        cCode += `}\n\nvoid loop() {\n}\n`;
    } else {
        cCode += `    return 0;\n}\n`;
    }

    state.editor.setValue(cCode);

    document.getElementById("status-text").textContent = "App Executed";
    setTimeout(() => {
        document.getElementById("status-text").textContent = "Ready";
    }, 2000);

    return cCode;
}

function getWidgetTypeName(type) {
    const typeMap = {
        button: "GooeyButton",
        textbox: "GooeyTextbox",
        slider: "GooeySlider",
        checkbox: "GooeyCheckbox",
        label: "GooeyLabel",
        canvas: "GooeyCanvas",
        image: "GooeyImage",
        dropsurface: "GooeyDropSurface",
        dropdown: "GooeyDropdown",
        list: "GooeyList",
        progressbar: "GooeyProgressBar",
        meter: "GooeyMeter",
        gswitch: "GooeySwitch",
        container: "GooeyContainer",
        tabs: "GooeyTabs",
        plot: "GooeyPlot",
        radiobuttongroup: "GooeyRadioButtonGroup",
    };

    return (
        typeMap[type] || `Gooey${type.charAt(0).toUpperCase() + type.slice(1)}`
    );
}
