const state = {
    editor: null,
    callbackEditor: null,
    uiXmlEditor: null,
    projectXml: null,
    previewContent: null,
    previewWindow: null,
    previewTitleBar: null,
    selectedWidget: null,
    draggedWidget: null,
    dragOffsetX: 0,
    dragOffsetY: 0,
    resizingWidget: null,
    resizeStartWidth: 0,
    resizeStartHeight: 0,
    resizeStartX: 0,
    resizeStartY: 0,
    widgetCallbacks: {},
    currentEditingWidget: null,
    isDropdownInit: false,
    isListInit: false,
    selectedPlatform: null,
    projectSettings: {
        name: null,
        platform: null,
        language: "c",
        frameworkVersion: "1.0.1",
    },
    widgetTypes: {
        Button: "GooeyButton",
        Canvas: "GooeyCanvas",
        Checkbox: "GooeyCheckbox",
        Container: "GooeyContainer",
        DropSurface: "GooeyDropSurface",
        Dropdown: "GooeyDropdown",
        FDialog: "GooeyFDialog",
        Image: "GooeyImage",
        Label: "GooeyLabel",
        Layout: "GooeyLayout",
        List: "GooeyList",
        Menu: "GooeyMenu",
        Meter: "GooeyMeter",
        NodeEditor: "GooeyNodeEditor",
        Notifications: "GooeyNotifications",
        Plot: "GooeyPlot",
        Progressbar: "GooeyProgressBar",
        RadioButtonGroup: "GooeyRadioButtonGroup",
        Slider: "GooeySlider",
        Switch: "GooeySwitch",
        Tabs: "GooeyTabs",
        Input: "GooeyTextbox",
        Overlay: "GooeyOverlay",
        VerticalLayout: "GooeyLayout",
        HorizontalLayout: "GooeyLayout",
    },
    widgetHierarchy: new Map(),
    widgetVarNames: new Map(),
    widgetCounter: 0,
    widgetMacroNames: new Map(),
};
export default state;
